version: "3.1"

services:
  db:
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    image: timescale/timescaledb-postgis:latest-pg10
    restart: always
    ports:
      - 5433:5432

  core:
    container_name: core
    depends_on: 
      - db
    environment:
      - JAVA_OPTS="-Xms384m -Xmx384m"
    image: niledb/core
    links:
      - db
    ports:
      - 80:80
      - 1883:1883
    restart: always

  dataflow:
    container_name: dataflow
    depends_on:
      - core
    image: niledb/dataflow:latest
    links:
      - core
      - db
    ports:
      - 8080:8080
    restart: always

  pgweb:
    container_name: pgweb
    depends_on:
      - db
    image: sosedoff/pgweb
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/niledb?sslmode=disable
    ports:
      - 8081:8081
    restart: always
